version: '3.8'

services:
  # MongoDB service (no authentication for development)
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--bind_ip_all", "--noauth"]
    networks:
      - cesizen-network

  # MongoDB Express web-based admin interface (optional)
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - cesizen-network

  # Auth service
  auth-service:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-for-development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=cesizen_auth
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com
    depends_on:
      - mongo
    networks:
      - cesizen-network

networks:
  cesizen-network:
    driver: bridge

volumes:
  mongo_data: